### ISSUE TITLE
Conversion Failure (0xEE, sub-type 0x05)

### ISSUE THREAD

**Issue by cirience-zz** [cpetrich/zs2decode#3]
Hi cpetrich,

I'm not abled to convert a .zs2 into a .xml with your program. It's returning an error. 

```python
Traceback (most recent call last):
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\notebooks\docs\convert.py", line 11, in <module>
    raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 82, in data_stream_to_chunks
    next_start = _skip_past_data_aa(data_stream, cont)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 180, in _skip_past_data_aa
    raise TypeError('Unexpected block format for 0xAA (0x%x) with marger 0x%x at 0x%x.' % (_ord(data_stream[start]),start))
TypeError: not enough arguments for format string
```

**Comment by cpetrich** [comment]
I fixed the parameter list of the error message. Can you run it again with the most recent version of zs2decode?

**Comment by cirience-zz** [comment]
Thank you very much for your fast answer! I ran the code again today.

The error message seems to be fixed now.
```
Traceback (most recent call last):
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\notebooks\docs\convert.py", line 12, in <module>
    raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 82, in data_stream_to_chunks
    next_start = _skip_past_data_aa(data_stream, cont)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 182, in _skip_past_data_aa
    start))
TypeError: Unexpected block format for 0xAA (0xaa) with marker 0x8002 at 0x663bf1.
```

**Comment by cpetrich** [comment]
Thanks! The string marker check in that function was too restrictive and failed on very long strings. I've changed it to be in line with the rest of the code. Would appreciate hearing if it works with the most recent version.

**Comment by SHA-256** [comment]
Thanks for your help! The program is now returning another error.
```
Traceback (most recent call last):
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 192, in _skip_past_data_ee
    byte_length={0x11:1, 0x04:4, 0x16: 4, 0x00: 0}[data_type]
KeyError: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\notebooks\docs\convert.py", line 12, in <module>
    raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 80, in data_stream_to_chunks
    next_start = _skip_past_data_ee(data_stream, cont)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 194, in _skip_past_data_ee
    raise TypeError('Unknown data type 0x%2x in block 0xEE at 0x%x.' % (data_type, start))
TypeError: Unknown data type 0x 5 in block 0xEE at 0x7d8abb.
```

**Comment by cirience-zz** [comment]
I'd like to thank you very much for all the help you've provided. Sadly the program is now return another error.
```
Traceback (most recent call last):
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 192, in _skip_past_data_ee
    byte_length={0x11:1, 0x04:4, 0x16: 4, 0x00: 0}[data_type]
KeyError: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\notebooks\docs\convert.py", line 12, in <module>
    raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 80, in data_stream_to_chunks
    next_start = _skip_past_data_ee(data_stream, cont)
  File "C:\Users\martin\Desktop\WinPython-32bit-3.5.3.1Qt5\python-3.5.3\lib\site-packages\zs2decode\parser.py", line 194, in _skip_past_data_ee
    raise TypeError('Unknown data type 0x%2x in block 0xEE at 0x%x.' % (data_type, start))
TypeError: Unknown data type 0x 5 in block 0xEE at 0x7d8abb.
```

**Comment by cpetrich** [comment]
This is cool: your file contains a data format I hadn't come across before. I can have a look into this if you run the following script on your .zs2 file and share the output with me.

```
import base64
import zs2decode.parser as parser
filename='<replace-with-filename.zs2>'
start=s0=0x7d8abb
data = parser.load(filename)
while True:
    s0 = parser._find_next_parameter(data, s0)
    coming_type = s0+data[s0]+1
    if data[coming_type]//16 == data[coming_type]&15:
        break
print('0x%x: %s'%(start-64,''.join(['%c' % v for v in base64.b64encode(data[start-64:coming_type+64])])))
```

**Comment by NKlinke** [comment]
Hi cpetrich,
I am also having some trouble with your software which I would love to use to convert a large set of test data into a database. 

I also have the datatype issue, so i ran your data format extraction code piece. You code piece seems to get stuck in some kind of infinite loop. At least it ran for 1h without any output. Do you have some other suggestion how to test? 

Initial error: 
```
D:\temp\zs2_decode>D:\TRB_CAE\Python\Anaconda3\python.exe zs2_to_xml.py
Traceback (most recent call last):
  File "D:\TRB_CAE\Python\Anaconda3\lib\site-packages\zs2decode-0.1-py3.5.egg\zs
2decode\parser.py", line 192, in _skip_past_data_ee
    byte_length={0x11:1, 0x04:4, 0x16: 4, 0x00: 0}[data_type]
KeyError: 5
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "zs2_to_xml.py", line 11, in <module>
    raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
  File "D:\TRB_CAE\Python\Anaconda3\lib\site-packages\zs2decode-0.1-py3.5.egg\zs
2decode\parser.py", line 80, in data_stream_to_chunks
    next_start = _skip_past_data_ee(data_stream, cont)
  File "D:\TRB_CAE\Python\Anaconda3\lib\site-packages\zs2decode-0.1-py3.5.egg\zs
2decode\parser.py", line 194, in _skip_past_data_ee
    raise TypeError('Unknown data type 0x%2x in block 0xEE at 0x%x.' % (data_typ
e, start))
TypeError: Unknown data type 0x 5 in block 0xEE at 0x76f312.
```

Hoping you can help me with this. 
Kind Regards

**Comment by cpetrich** [comment]
Hi NKlinke,

thanks for checking, and sorry the code didn't terminate on your file. Try this:
```
import base64
import zs2decode.parser as parser
filename='<replace-with-filename.zs2>'
start = 0x76f312
end = start + 0x4000
data = parser.load(filename)
output = '0x%x: %s'%(start-64,''.join(['%c' % v for v in base64.b64encode(data[start-64:end])]))
with open('zs2_excerpt.txt','w') as f:
    f.write(output)
```
then upload the generated text file to a temporary file storage site and post the link. I'll have a look at it.

**Comment by NKlinke** [comment]
Okay. I will post the file here. Thanks for your help

[zs2_excerpt.txt](https://github.com/cpetrich/zs2decode/files/1274437/zs2_excerpt.txt)

**Comment by cpetrich** [comment]
Thanks. Looks like double precision floats. Couldn't test it, so could you try with the current version in the master branch and let me know how it goes?

**Comment by NKlinke** [comment]
You newest version unfortunately was raising the following: 

```
D:\Optimization\zs2_decode>python35 zs2_to_xml.py
Traceback (most recent call last):
  File "zs2_to_xml.py", line 11, in <module>
    raw_chunks = zs2decode.parser.data_stream_to_chunks(data_stream)
  File "D:\TRB_CAE\Python\Anaconda3\lib\site-packages\zs2decode\parser.py", line 82, in data_stream_to_chunks
    next_start = _skip_past_data_aa(data_stream, cont)
  File "D:\TRB_CAE\Python\Anaconda3\lib\site-packages\zs2decode\parser.py", line 180, in _skip_past_data_aa
    raise TypeError('Unexpected block format for 0xAA (0x%x) with marger 0x%x at 0x%x.' % (_ord(data_stream[start]),start))
TypeError: not enough arguments for format string
```

**Comment by cpetrich** [comment]
That's actually an older version of the file and has been fixed. 

Can you try the current version from here?
https://github.com/cpetrich/zs2decode/blob/master/src/zs2decode/parser.py

Thanks

**Comment by NKlinke** [comment]
Oh. Sorry for that. Actually the zs2_to_xml.py now works without any Exceptions. But i am kind of confused by the output format. I thought the utility was generating an xml? This is what i get: 

```
000004: Document [DD] '' 
00000f:   Header [DD] '' 
000018:     Magic [66] 0 
000021:     Typ [66] 0 
000028:     DocInfoVersion [11] 3 
00003c:     StoreCount [44] 2558 
........
```

**Comment by cpetrich** [comment]
that's the output of `utils.chunks_to_text_dump()`. Can you make sure your conversion script is calling `util.chunks_to_XML()` instead?

**Comment by NKlinke** [comment]
Thank you for your help and sorry to bother you again. It seems that the generated xml has some encoding issues: 
```
D:\temp\zs2_decode>python35 zs2_to_xml.py

D:\temp\zs2_decode>python35 raw_data_dump_from_xml.py
Reading XML
Parsing XML
Traceback (most recent call last):
  File "raw_data_dump_from_xml.py", line 13, in <module>
    root = ET.fromstring(data)
  File "D:\TRB_CAE\Python\Anaconda3\lib\xml\etree\ElementTree.py", line 1333, in
 XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 240740,
column 13
```

line 240740
```
          <nt&)m_Type type='11' value='0' />
```
Correcting this manually leads to another conversion issue: 
```
D:\temp\zs2_decode>python35 raw_data_dump_from_xml.py
Reading XML
Parsing XML
Traceback (most recent call last):
  File "raw_data_dump_from_xml.py", line 13, in <module>
    root = ET.fromstring(data)
  File "D:\TRB_CAE\Python\Anaconda3\lib\xml\etree\ElementTree.py", line 1333, in
 XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 243095,
column 12
```
line 243095
```
<VideoDirectory type='AA' value='C:\\ZWICK\\V3.2 B\\VIDEO\&apos; />
```

**Comment by cpetrich** [comment]
thanks for your feedback and for hanging in there. 
Since the original issue parsing sub-type 0x05 in data types 0xEE seems to have been resolved I'm closing this issue and open a new one on the XML encoding problem you mention  ( #4 ).
