### ISSUE TITLE
malformatted entity substitution in XML

### ISSUE THREAD

**Issue by cpetrich** [cpetrich/zs2decode#4]
@NKlinke pointed out that xml generated with `util.chunks_to_xml()` has encoding issues: 

```
D:\temp\zs2_decode>python35 zs2_to_xml.py

D:\temp\zs2_decode>python35 raw_data_dump_from_xml.py
Reading XML
Parsing XML
Traceback (most recent call last):
  File "raw_data_dump_from_xml.py", line 13, in <module>
    root = ET.fromstring(data)
  File "D:\TRB_CAE\Python\Anaconda3\lib\xml\etree\ElementTree.py", line 1333, in
 XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 240740,
column 13
```

line 240740
```
          <nt&)m_Type type='11' value='0' />
```
Correcting this manually leads to another conversion issue: 
```
D:\temp\zs2_decode>python35 raw_data_dump_from_xml.py
Reading XML
Parsing XML
Traceback (most recent call last):
  File "raw_data_dump_from_xml.py", line 13, in <module>
    root = ET.fromstring(data)
  File "D:\TRB_CAE\Python\Anaconda3\lib\xml\etree\ElementTree.py", line 1333, in
 XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 243095,
column 12
```
line 243095
```
<VideoDirectory type='AA' value='C:\\ZWICK\\V3.2 B\\VIDEO\&apos; />
```

**Comment by cpetrich** [comment]
thanks for this! 
Looks like the code for XML generation needs to be refactored to depend on a properly tested library for XML generation. Will do later this week.

**Comment by cpetrich** [comment]
Refactored the XML conversion. in `util.py`, also changed `raw_data_dump_from_xml.py`.
Does this work for you?

**Comment by NKlinke** [comment]
Hi, the refactored version works fine. Thank you for your fast support and the tool itself!

**Comment by cpetrich** [comment]
thank you for your reports and feedback.
